# Site settings
title: Seongjae Lee
email: seongjae@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seongjaelee.github.io" # the base hostname & protocol for your site
lang: ko
disqusid: seongjaelee

# Build settings
markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed
