# Site settings
title: Seongjae Lee
email: seongjae@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://seongjaelee.github.io" # the base hostname & protocol for your site
lang: ko
disqusid: seongjaelee
social:
  name: Seongjae Lee
  links:
    - https://www.linkedin.com/in/seongjae-lee-23028359

# Build settings
markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
